packages:
  - .

ignoredBuiltDependencies:
  - cypress
  - electron
  - electron-winstaller
  - esbuild

overrides:
  courthive-components: link:../courthive-components
  tods-competition-factory: link:../factory
