export const lang = (function () {
  let lang = {};
  let idioms = {};
  let selected_ioc = 'gbr';

  lang.define = ({ ioc, idiom }) => {
    idioms[ioc] = idiom;
  };

  lang.set = (new_ioc) => {
    if (!new_ioc) return selected_ioc;
    if (!idioms[new_ioc]) return;
    selected_ioc = new_ioc;
    return idioms[new_ioc];
  };

  lang.options = () => Object.keys(idioms);
  lang.current = () => idioms[selected_ioc];

  function translate(what) {
    if (!what) return '';
    let obj = idioms[selected_ioc];
    let children = what.split('.');
    while (children.length) {
      let child = children.shift();
      obj = obj?.[child] || '';
    }
    return obj;
  }

  // fall back to English if not found in idiom
  lang.tr = (what) => {
    if (!what) return '';
    if (translate(what)) return translate(what);
    let obj = idioms.default;
    let children = what.split('.');
    while (children.length) {
      let child = children.shift();
      obj = obj?.[child] || '';
    }
    return obj;
  };

  lang.obj = (what) => {
    if (!what) return '';
    if (idioms?.[selected_ioc]?.[what]) return idioms[selected_ioc][what];
    if (idioms.default[what]) return idioms.default[what];
    return {};
  };

  idioms.default = {
    open: 'Open',
    zoom: 'Zoom',
    addcourts: 'Add Courts',
    login: 'Login',
    logout: 'Logout',
    passwd: 'Password',
    lang: 'Language',
    menu: 'Menu',
    main: 'Main Menu',
    local: 'Local Data',
    save: 'Save',
    side: 'Side',
    bye: 'BYE',
    select: 'Select',
    selected: 'Selectd',
    group: 'GROUP',
    administrator: 'Administrator',
    revoke: 'Revoke',
    tour: 'Tour',
    noresults: 'No Results',
    delete: 'Delete',
    continue: 'Do you wish to continue?',
    notes: 'Notes',
    social: 'Social Media',
    stats: 'Statistics',
    merge: 'Merge',
    week: 'Week',
    warn: 'WARNING',
    add: 'Add',
    remove: 'Remove',
    ptz: 'Penalties',
    replace: 'Replace',
    dl: 'Download',
    or: 'or',
    arp: 'All Ranking Points',
    rlp: 'Points - Ranking Lists',
    trn: 'Tournament',
    tnz: 'Tournaments',
    enable: 'Enable',
    disable: 'Disable',
    rnd: 'Round',
    dt: 'Date',
    fmt: 'Format',
    cat: 'Category',
    cta: 'Cat.',
    team: 'Team',
    tmz: 'Teams',
    rnk: 'Rank',
    rnkz: 'Rankings',
    rtg: 'Rating',
    rtz: 'Ratings',
    prnk: 'Rank', // player rank
    trnk: 'Rank', // tournament rank
    rl: 'Rank List',
    rlo: 'Rank Order',
    alpha: 'Alphabetical',
    opnt: 'Opponent',
    ply: 'Player',
    pyr: 'Players',
    sgi: 'Sign-In',
    sgo: 'Sign-Out',
    scr: 'Score',
    pts: 'Points',
    allmatches: 'All Matches',
    allteams: 'All Teams',
    mts: 'Matches',
    emts: 'Matches',
    ests: 'Sets',
    egms: 'Games',
    epts: 'Points',
    mtc: 'Match',
    drw: 'Draw',
    drz: 'Draws',
    ent: 'Event',
    evt: 'Events',
    sch: 'Schedule',
    rename: 'Rename',
    crt: 'Courts',
    ct: 'Court',
    on: 'On',
    off: 'Off',
    id: 'ID',
    nm: 'Name',
    fnm: 'First Name',
    lnm: 'Last Name',
    nnm: 'Nickname',
    attr: 'Attribute',
    bd: 'Birthday',
    yr: 'Year',
    byr: 'Birth Year',
    tot: 'Total',
    sgl: 'Singles',
    dbl: 'Doubles',
    pyo: 'Playoff',
    adh: 'Ad-Hoc',
    snr: 'Senior',
    unk: 'Unknown',
    dup: 'Duplicate',
    stt: 'Status',
    ord: 'Order',
    clb: 'Club',
    scl: 'School',
    cty: 'City',
    state: 'State',
    cnt: 'Country',
    kwn: 'Known',
    ioc: 'IOC',
    act: 'Action',
    agd: 'Assigned',
    igr: 'Ignore',
    igd: 'Ignored',
    edt: 'Edit Player',
    idp: 'Identify Player',
    dlp: 'Delete Player',
    sbt: 'Submit',
    ccl: 'Cancel',
    clr: 'Clear',
    und: 'Undo',
    apt: 'Accept',
    dss: 'Dismiss',
    frm: 'From',
    to: 'To',
    h2h: 'Head-to-Head',
    reg: 'Registered',
    gdr: 'Gender',
    dtp: 'Draw Type',
    drp: 'Draw Position',
    manual: 'Manual Draw',
    adr: 'Automated Draw',
    mdo: 'Draw Order',
    phn: 'Phone',
    view: 'View',
    email: 'Email',
    asn: 'Association',
    start: 'Start',
    end: 'End',
    dates: 'Dates',
    ref: 'Referee',
    time: 'Time',
    duration: 'Duration',
    qualifier: 'Qualifier',
    qualifiers: 'Qualifiers',
    none: 'None',
    keys: 'Keys',
    pos: 'Position',
    seeding: 'Seeding',
    home: 'Home',
    new: 'New',
    inout: 'In/Out',
    indoors: 'Indoors',
    outdoors: 'Outdoors',
    existing: 'Existing',
    success: 'Success',
    loading: 'Loading',

    set: 'Settings',
    version: 'Version',
    messages: 'Messages',
    support: 'Support',
    datastorage: 'Data Storage',
    releasenotes: 'Release Notes',
    documentation: 'Documentation',
    importexport: 'Import / Export',
    newversion: 'New Version Available',

    latitude: 'Latitude',
    longitude: 'Longitude',

    i18n: {
      previousMonth: 'Previous Month',
      nextMonth: 'Next Month',
      months: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December'
      ],
      monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      weekdaysShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
    },

    settings: {
      help: 'Help',
      pagesize: 'Page Size',
      schedule: 'Schedule',
      calendar: 'Calendar',
      search: 'Search',
      documentation: 'Documentation Links',
      hoverhelp: 'Hover Hints',
      diacritics: 'Diacritics',
      lastfirst: 'Last name, First name',
      organization: 'Organization',
      general: 'General',
      categories: 'Categories',
      points: 'Points',
      draws: 'Draws',
      data: 'Data',
      sheetdata: 'Sheet Data',
      publishing: 'Publishing',
      printing: 'Printing',
      savepdfs: 'Save PDF',
      opentabs: 'Open in Browser Tabs',
      compresseddraws: 'Compressed Draw Formats',
      teams: 'Teams Displayed',
      countryflags: 'Country Flags Displayed',
      requireconfirm: 'Require Confirmation',
      publishonscore: 'Publish when score entered',
      publishdrawcreation: 'Publish as draw created',
      matchesbefore: 'Matches Before Count',
      automatedbyes: 'Automatic Bye Placement',
      llallrounds: 'LL from All Qualifying Rounds',
      rrh2hpriority: 'RR Head-to-Head priority',
      qualconsolation: 'Qualifying Consolation',
      consolationalts: 'Consolation Alternates',
      consolationseeds: 'Consolation Seeding',
      gemseeding: 'GEM Seeding',
      adhocelo: 'Adhoc ELO Ratings',
      restrictseedplacement: 'Restrict Seed Placement',

      separate_by_team: 'Auto Separate Players by Team',
      separate_by_ioc: 'Auto Separate Players by Country', // will be removed
      separate_by_club: 'Auto Separate Players by Club', // will be removed
      separate_by_school: 'Auto Separate Players by School', // will be removed
      clear_separation: 'Clear Auto Separation', // will be removed

      courtdetail: 'Court Details',
      matchtimes: 'Match Times',
      matchdates: 'Match Dates',
      firstday: 'Week Starts Monday',
      time24: '24 Hour Clock',
      draworderscores: 'Scores in Draw Order',
      schedulecompleted: 'Schedule Completed Matches',
      courtidentifiers: 'court identifiers'
    },

    round_names: {
      F: 'Final',
      SF: 'Semifinal',
      QF: 'Quarterfinal'
    },

    search: {
      filterplayers: 'Filter Players',
      players: 'Search Players',
      tournaments: 'Search Tournaments',
      clubs: 'Search Clubs',
      approve: 'Approve Player',
      add2team: 'Add Team Player',
      lastfirst: 'LAST First',
      firstlast: 'First Last'
    },

    formats: {
      singles: 'Singles',
      doubles: 'Doubles',
      team: 'Team'
    },

    scoring_format: {
      set: 'Set',
      sets: 'Sets',
      timedset: 'Timed Set',
      timedsets: 'Timed Sets',
      tiebreak: 'Tiebreak',
      tiebreaks: 'Tiebreaks',
      winby: 'Win By',
      custom: 'Custom',
      bestof: 'Best of',
      tbat: 'TB at',
      finalset: 'Final Set',
      setsto: 'Sets to',
      tbto: 'TB to',
      superto: 'To'
    },

    // eslint-disable-next-line no-dupe-keys
    scoring: {
      label: 'Scoring',
      retire: 'Retire',
      default: 'Default',
      walkover: 'Walkover',
      supertiebreak: 'Match Tiebreak',
      normal: 'Normal',
      winloss_abbreviation: 'W/L',
      cancelled: 'Cancelled', // unused
      abandoned: 'Abandoned' // unused
    },

    draws: {
      seedlimit: 'Seed Limit',
      blockthreshold: 'Block Threshold',
      generating: 'Generating... Please be patient...',
      generateround: 'Generate Round',
      deleteround: 'Delete Round',
      adhoc: 'Adhoc',
      gemseeding: 'GEM Seeding',
      playerfilter: 'Ratings Filter',
      compass: 'Compass',
      north: 'North',
      south: 'South',
      east: 'East',
      west: 'West',
      northeast: 'Northeast',
      northwest: 'Northwest',
      southeast: 'Southeast',
      southwest: 'Southwest',
      feedin: 'Feed-in',
      staggered: 'Staggered',
      standard: 'Standard',
      elective: 'Elective',
      backdraw: 'Backdraw',
      roundlimit: 'Round Limit',
      structure: 'Structure',
      skiprounds: 'Skip Rounds',
      feedrounds: 'Feed Rounds',
      sequential: 'Sequential',
      brackets: 'Brackets',
      bracketsize: 'Bracket Size',
      roundrobin: 'Round Robin',
      elimination: 'Elimination',
      consolation: 'Consolation',
      qualification: 'Qualification',
      preround: 'Pre-Round',
      incidentals: 'Incidentals',
      remove: 'Remove',
      changestatus: 'Change Status',
      penalty: 'Assess Penalty',
      umpire: 'Select Referee',
      matchumpire: 'Match Referee',
      matchtime: 'Match Time',
      starttime: 'Start Time',
      endtime: 'Finish Time',
      resttime: 'Rest Time',
      duration: 'Duration',
      timeheader: 'Time Heading',
      maindraw: 'Main Draw',
      unscheduled: 'Unscheduled Matches',
      scheduled: 'Scheduled Matches',
      completed: 'Completed',
      unpublished: 'Unpublished',
      publisheduptodate: 'Up to Date',
      publishedoutofdate: 'Out of Date',
      published: 'Published',
      publish: 'Publish',
      publishQ: 'Publish Draw?',
      organizers: 'Organizers',
      playerrep: 'Representative',
      playerreps: 'Representatives',
      substitutes: 'Substitutes (LL/Alts)',
      allindraw: 'all in draw',
      lastdirectaccept: 'Last Direct Acceptance',
      clear: 'Clear Draw',
      swap: 'Swap Position',
      alternate: 'Alternate',
      alternatepair: 'Alternate Pair',
      alternateplayer: 'Alternate Player',
      luckyloser: 'Lucky Loser',
      first: 'First',
      last: 'Last',
      seedrange: 'Seeds',
      modifyseeding: 'Modify Seeding',
      playerrange: 'All Players',
      unpublish: 'Unpublish Draw',
      unpublishall: 'Unpublish All Events'
    },

    print: {
      publishpdf: 'Publish PDF',
      schedule: 'Schedule',
      draw: 'Print',
      signin: 'Sign-In Sheet',
      ranklist: 'Rank List',
      playerlist: 'Player List',
      matchlist: 'Print Match List',
      matchesbytime: 'Matches by Time',
      pendingmatches: 'Pending Matches',
      matchesbycourt: 'Matches by Court',
      completedmatches: 'Completed Matches'
    },

    teams: {
      code: 'Code (3 letters)',
      name: 'Name',
      share: 'Share Team',
      rankings: 'Team Rankings',
      members: 'Members',
      matches: 'Matches',
      winloss: 'Won/Lost',
      newteam: 'New Team',
      createnew: 'Create New',
      submitkey: 'Submit Key',
      nameorkey: 'Team Name or Import Key',
      club: 'Club',
      coaches: 'Coaches',
      school: 'School',
      ioc: 'Country',
      abbreviation: 'Abbreviation'
    },

    tournament: {
      organizer_email: 'Organizer Email',
      organizer_phone: 'Organizer Phone',
      judge_email: 'Referee Email',
      judge_phone: 'Referee Phone',
      sponsor: 'Sponsor(s)',
      logo: 'Tournament Logo',
      images: 'Tournament Images'
    },

    tournaments: {
      type: 'Type',
      standard: 'Standard',
      dual: 'Dual Matches',
      register: 'Register',
      registration: 'Registration Link',
      team: 'Team Tournament',
      new: 'New Tournament',
      add: 'Add Tournament',
      id: 'Tournament ID',
      loadbyid: 'Load by ID',
      edit: 'Edit',
      copy: 'Copy',
      close: 'Close',
      done: 'Finish',
      import: 'Import Record',
      removeall: 'Remove All',
      addall: 'Add All',
      destroyall: 'Destroy All',
      key: 'Authorization',
      noauth: 'Not Authorized',
      unofficial: 'Unofficial',
      auth: 'Authorized',
      fetch: 'Download',
      fetchtournament: 'Download Tournament Record',
      convert: 'Convert to TODS / Save',
      send: 'Upload Tournament Record',
      export: 'Export Tournament Record',
      // mergeevents: 'Merge Events from server',
      renewlist: 'Renew List',
      natlassoc: 'National Association',
      tennisclub: 'Tennis Club',
      received: 'Received Tournament Record',
      existing: 'Existing Tournament Record',
      publishtime: 'Publish Time',
      replacelocal: 'Replace Local Copy?',
      unpublish: 'Unpublish Tournament?'
    },

    ddlb: {
      singles: 'Singles Tournament Rank:',
      doubles: 'Doubles Tournament Rank:',
      category: 'Tournament Category:',
      draws: 'Select Event:',
      direction: 'Select Draw:'
    },

    phrases: {
      remember_me: 'Remember Me',
      forgot_passwd: 'Forgot Password',
      no_account: 'No account? Sign Up',
      selectlanguage: 'Select Language',
      setupcourts: 'Set up your courts',
      courtsmsg:
        'Before you can schedule matches we need to know more about your courts. To get started, add some court details.',
      sortorder: 'Sort Order',
      eventcorrupted: 'Event is Corrupted: Development Notified',
      singlesrankings: 'Singles Rankings',
      doublesrankings: 'Doubles Rankings',
      sectionscroll: 'Section Scrolling',
      dynamicrating: 'Dynamic Rating',
      recalcdynamic: 'Re-Calculate Dynamic Rating',
      comingsoon: 'New Feature: Coming Soon!',
      finalrounds: 'Final Rounds',
      sendplayerdb: 'Send Player Database',
      prerelease: 'Pre-release version of TMX',
      feedback: 'Please send all feedback and support requests to',
      improperauth: 'Improper Authorization Credentials',
      noexportformats: 'No Export Formats Enabled',
      verifyranking: 'Please Verify Player Ranking!',
      nomatches2schedule: 'No Matches to Schedule!',
      addimage: 'Enter full website address for an image',
      addgooglemap: 'Enter full URL, not "Link to Share"',
      retrieveFromServer: 'Retrieve from CourtHive Server?',
      mainmenu: 'Main Menu',
      rankbyrating: 'Rank by Rating',
      dblsrankisrating: 'Use Rating as Doubles Ranking?', // deprecated
      sheetdataurls: 'Enter Google Sheet URLs for Synchronizing Data',
      playerimport: 'Player Import',
      entersheeturl: 'Enter Sheet URL',
      entergooglemapsurl: 'Enter Google Maps link',
      invalidurl: 'Invalid URL(s)',
      invalidsheeturl: 'Invalid Sheet URL',
      invalidgooglemapsurl: 'Invalid Google Maps Link',
      geolocationdenied: 'Geolocation has been denied',
      unblockgeo: 'Unblock in browser settings',
      usecurrentlocation: 'Use your current position?',
      updatelatlng: 'Update Latitude/Longitude?',
      cleardraw: 'Existing Draw will be cleared!',
      clearselection: 'Clear Selection',
      selectplayer: 'Select Player',
      matches2clear: 'Matches to be cleared from the schedule',
      changeapproved: 'Changing Approved will reset the draw and clear the schedule.',
      qualincomplete: 'Qualifying Draw is Incomplete',
      delegate: 'Delegate',
      delegate2mobile: 'Delegate to Mobile',
      revokedelegation: 'Revoke Delegation',
      delegationrevoked: 'Delegation has been revoked',
      qrcode: 'QR Code',
      scanQRcode: 'Scan QR Code with Mobile',
      ranklists: 'Rank Lists for',
      reset: 'Database will be reset',
      action: 'Players requiring some action...',
      search: 'Use the search field above to find players, or click player to edit',
      assign: 'Assign this profile by clicking a player below, or ...',
      accept: 'Accept all players',
      trnyz: 'Loading Tournaments ...',
      loadplayers: 'Load Players',
      badfile: 'File Not Recognized',
      invalid: 'Invalid file type',
      fileerror: 'Error reading file',
      servererror: 'Error Message from Server',
      notfound: 'Not Found',
      pointcalc: 'Point calculation requires tournament category and rank',
      drawcreated: 'Draw Created',
      drawactive: 'Active Draw',
      notcreated: 'Not Created',
      importdata: 'Import Data',
      exportdata: 'Export Data',
      importtemplate: 'Import Template',
      draganddrop: 'Drag and Drop files into this zone',
      schedulematches: 'Schedule Matches',
      notconfigured: 'Not Configured',
      cannotsignout: 'Cannot Sign Out',
      cannotchangerank: 'Cannot Change Rank',
      cannotchangewinner: 'Cannot Change Winner',
      matchmustbecomplete: 'Match Must Be Complete!',
      approvedplayer: 'Player Approved for an Event',
      locallycreated: 'Locally Created Tournament',
      noremote: 'No Remote Registrations to Update',
      calculateranking: 'Calculate Ranking Points',
      generateranklist: 'Generate Rank List',
      generatekey: 'Generate Key',
      norankingdata: 'No Ranking Data',
      oop_system: 'Order of Play',
      schedulepublished: 'Publishing Time:',
      timestamp: 'Date/Time: ',
      rankedplayers: 'Ranked Players',
      judgesignature: 'Signature of Head Umpire:',
      nopointcalcs: 'No Point Calculations for given date',
      downloadtemplate: 'Download Import Template',
      add2database: 'Add Players, Tournaments, Rankings to Database',
      noconnection: 'No Connection',
      schedulepriority: 'Match Scheduling Priority',
      send: 'Send',
      sendTODS: 'Send TODS Tournament Record',
      export: 'Export',
      pointsvalidfrom: 'Points Valid From',
      linkcopied: 'Link Copied to Clipboard',
      keycopied: 'Key Copied to Clipboard',
      submitkey: 'Enter New Key',
      selectkey: 'Select Key',
      deletereplace: 'Delete / Replace',
      weblink: 'Web Link',
      nomatches: 'No Matches',
      updatedioc: 'Update Language File',
      revokeauth: 'Revoke Authorization?',
      clearalldays: 'Clear All Days?',
      cantdelqual: 'Cannot Delete: Qualified Player Active in Main Draw',
      cantrefresh: 'Offline: Cannot Refresh',
      blocked: 'Pop-Up Windows are blocked by your browser',
      enablepopups: 'Please enable Pop-Ups for PDF printing',
      nopersist: 'Data Persistence not guaranteed'
    },

    events: {
      name: 'Name',
      newevent: 'New Event',
      customname: 'Custom Name',
      enableeligibility: 'Enable Eligibility Filter',
      disableeligibility: 'Disable Eligibility Filter',
      teamevent: 'Team Event',
      opponents: 'Opponents',
      matchprofile: 'Match Profile',
      teams: 'Teams',
      draw_type: 'Draw Type',
      draw_size: 'Draw Size',
      created: 'Created',
      category: 'Category',
      rank: 'Rank',
      surface: 'Surface',
      approveteam: 'Approve',
      destroyteam: 'Destroy',
      entered: 'Entered',
      approved: 'Approved',
      eligible: 'Eligible',
      ineligible: 'Ineligible',
      unavailable: 'Unavailable',
      wildcard: 'Wildcard',
      received: 'Received Event(s)',
      toggle: 'Toggle Publish State?',
      modifyranking: 'Modify Ranking'
    },

    locations: {
      newlocation: 'New Location',
      abbreviation: 'Abbreviation',
      name: 'Name',
      address: 'Address',
      courts: 'Courts',
      identifiers: 'Court IDs'
    },

    genders: {
      male: 'Male',
      male_abbr: 'M',
      female: 'Female',
      female_abbr: 'W',
      mixed: 'Mixed'
    },

    surfaces: {
      clay: 'Clay',
      hard: 'Hard',
      grass: 'Grass',
      carpet: 'Carpet'
    },

    actions: {
      ok: 'OK',
      actions: 'Actions',
      add_event: 'Add Event',
      save_event: 'Save Event',
      save_team: 'Save Team',
      save_location: 'Save Location',
      done: 'Done',
      cancel: 'Cancel',
      refresh: 'Refresh',
      remakedraw: 'Remake Draw',
      delete_event: 'Delete Event',
      delete_team: 'Delete Team',
      delete_match: 'Delete Match',
      add_player: 'Add Player',
      add_team: 'Add Team',
      create_team: 'Create Team',
      generate_team: 'Generate Team',
      publish: 'Publish',
      unpublish: 'Unpublish',
      manage_players: 'Manage Players',
      manage_teams: 'Manage Teams',
      add_location: 'Add Location',
      delete_location: 'Delete Location',
      delete_tournament: 'Delete tournament',
      edit_tournament: 'Edit Tournament',
      copy_tournament: 'Copy Tournament',
      createteambyattr: 'Create Team',
      add2localdb: 'Add Players to Local Database',
      signoutunapproved: 'Sign Out players not approved for Events'
    },

    requests: {
      syncClubs: 'Synchronize Clubs',
      syncTournaments: 'Synchronize Tournaments',
      syncPlayers: 'Synchronize players'
    },

    signin: {
      tournament_date: 'Start Date',
      organization: 'Organization',
      place: 'Location',
      id: 'Tournament ID',
      rank: 'Tournament Rank',
      judge: 'Head Umpire',
      doc_name: 'SIGN-IN SHEET',
      doc_subname: ' ',
      signature: 'Signature',
      registered: 'Registered Players',
      notsignedin: 'Not Signed In',
      signedin: 'Signed In',
      withdrawn: 'Withdrawn',
      medical: 'Medical',
      registration: 'Registration',
      medical_issues: 'Medical Expired',
      create_new_player: 'Create New',
      modifyrankings: 'Modify Rankings',
      acceptrankings: 'Accept Rankings',
      reglink: 'Set Link'
    },

    schedule: {
      column: 'Column',
      rows: 'Schedule Rows',
      startrow: 'Start Row',
      alldraws: 'All Draws',
      allevents: 'All Events',
      allrounds: 'All Rounds',
      allcourts: 'All Courts',
      alldual: 'All Dual Matches',
      autoschedule: 'Auto Schedule',
      highlightteam: 'Highlight Team',
      limit: 'Limit',
      clearschedule: 'Clear Schedule',
      clearcompleted: 'Clear Completed Matches',
      orderofplay: 'ORDER OF PLAY',
      matchestime: 'Matches => Time',
      notbefore: 'Not Before',
      nb: 'NB',
      followedby: 'Followed By',
      afterrest: 'After Rest',
      raindelay: 'Rain Delay',
      tba: 'TBA',
      nextavailable: 'Next Available',
      called: 'Called',
      oncourt: 'On Court',
      warmingup: 'Warming Up',
      suspended: 'Suspended',
      abandoned: 'Abandoned',
      clear: 'Clear',
      publish: 'Publish Schedule',
      view: 'View Schedule',
      unpublish: 'Unpublish Schedule',
      timing: 'Timing',
      vs: 'vs.',
      umpirenotes: 'Umpire Notes',
      notice: 'Schedule Notice',
      opponentname: 'Opponent Name',
      scheduled: 'Scheduled'
    },

    /*
      refresh: {
         // general: 'Refresh',
         // roster: 'Updating Team Roster...',
         // registered: 'Updating Registered Players...',
         // players: 'Updating Players...',
         // calendar: 'Updating Calendar...',
         // clubs: 'Updating Clubs...'
      },
      */

    penalties: {
      fail2signout: 'Failed to Sign Out',
      illegalcoaching: 'Illegal Coaching',
      ballabuse: 'Ball Abuse',
      racquetabuse: 'Racquet Abuse',
      equipmentabuse: 'Equipment Abuse',
      cursing: 'Swearing',
      rudegestures: 'Rude Gestures',
      foullanguage: 'Foul Language',
      timeviolation: 'Time Violation',
      latearrival: 'Late Arrival',
      unsporting: 'Unsporting Behavior'
    },

    // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString
    datelocalization: 'en-EN'
  };

  return lang;
})();
