import type { APIRequestContext } from '@playwright/test';
import { mocksEngine } from 'tods-competition-factory';

import { SERVER, ensureProvider, uniqueAbbr, uniqueSuffix } from './role-fixtures';

/**
 * Server-side fixture for the participation (schedule) journey.
 *
 * Seeds the shape the read model exists for, and no simpler one: a GOVERNING provider that owns a
 * fixture, and TWO programme providers that both took part in it. That pairing is the whole point —
 * a tournament may live in exactly one calendar, so a fixture belonging to two programmes' seasons
 * cannot be expressed by calendar membership at all. A single-programme fixture would pass a test
 * that a calendar could also have passed.
 *
 * A third programme is seeded with NO fixtures, because "this subject took part in nothing" is an
 * ordinary correct answer that must not render as a failure, and the only way to assert that is to
 * have a subject genuinely in that state.
 *
 * The record is generated by `mocksEngine` with `completeAllMatchUps`, so drilling from the season
 * into a fixture reaches real matchUps carrying real results — the second half of the acceptance
 * journey. The TEAM participants are then attached on top: `deriveParticipationRows` reads
 * `participants[]` and `participantOtherIds`, independently of who is in a draw.
 */

const FIXTURE_DATE = '2026-03-04';

export interface SeededProgramme {
  providerId: string;
  name: string;
  abbr: string;
}

export interface ParticipationFixture {
  governingProviderId: string;
  governingAbbr: string;
  /** A conventional, calendar-LISTED tournament under the same governing body. It exists so the
   *  "the fixture is in no calendar" assertion has something to be non-degenerate against: an empty
   *  calendar would satisfy that assertion no matter what the seam did. */
  listedTournamentId: string;
  programmeA: SeededProgramme;
  programmeB: SeededProgramme;
  emptyProgramme: SeededProgramme;
  tournamentId: string;
  tournamentName: string;
  startDate: string;
}

const authHeaders = (token: string) => ({ Authorization: `Bearer ${token}` });

async function seedProgramme(
  request: APIRequestContext,
  token: string,
  tag: string,
  suffix: string,
): Promise<SeededProgramme> {
  const abbr = uniqueAbbr(tag);
  const name = `E2E Programme ${tag} ${suffix}`;
  const providerId = await ensureProvider(request, token, abbr, name);
  return { providerId, name, abbr };
}

/**
 * `participantOtherIds` carries the id the ISSUING ORGANISATION uses for this competitor, and for a
 * team-grain provider that id IS the provider's id. Never `participantId` — that one is
 * tournament-local, so keying on it would give every programme a season exactly one fixture long:
 * plausible, and wrong with nothing to signal it.
 */
function teamParticipant(programme: SeededProgramme, governingProviderId: string, localId: string) {
  return {
    participantId: localId,
    participantName: programme.name,
    participantType: 'TEAM',
    participantRole: 'COMPETITOR',
    participantOtherIds: [{ organisationId: governingProviderId, participantId: programme.providerId }],
  };
}

export async function seedParticipationFixture(
  request: APIRequestContext,
  token: string,
): Promise<ParticipationFixture> {
  const suffix = uniqueSuffix();

  const governingAbbr = uniqueAbbr('GOV');
  const governingProviderId = await ensureProvider(request, token, governingAbbr, `E2E Governing Body ${suffix}`);
  const programmeA = await seedProgramme(request, token, 'A', suffix);
  const programmeB = await seedProgramme(request, token, 'B', suffix);
  const emptyProgramme = await seedProgramme(request, token, 'Z', suffix);

  const tournamentName = `${programmeA.name} vs ${programmeB.name}`;
  const { tournamentRecord } = mocksEngine.generateTournamentRecord({
    nonRandom: 1,
    startDate: FIXTURE_DATE,
    endDate: FIXTURE_DATE,
    tournamentName,
    drawProfiles: [{ drawSize: 4, eventName: 'Dual Match' }],
    completeAllMatchUps: true,
  });

  tournamentRecord.parentOrganisation = { organisationId: governingProviderId };
  // `calendarListed: false` — the record is OWNED by the governing body and deliberately absent
  // from its calendar, exactly as the loaded duals are. An unlisted save does zero calendar IO.
  tournamentRecord.extensions = [...(tournamentRecord.extensions ?? []), { name: 'calendarListed', value: false }];
  tournamentRecord.participants = [
    ...(tournamentRecord.participants ?? []),
    teamParticipant(programmeA, governingProviderId, `${suffix}-team-a`),
    teamParticipant(programmeB, governingProviderId, `${suffix}-team-b`),
  ];

  await save(request, token, tournamentRecord);

  // The control tournament: same owner, ordinary listing, so the governing body's calendar is
  // provably non-empty and reachable when the journey asserts the fixture is NOT in it.
  const { tournamentRecord: listedRecord } = mocksEngine.generateTournamentRecord({
    nonRandom: 1,
    startDate: FIXTURE_DATE,
    endDate: FIXTURE_DATE,
    tournamentName: `E2E Listed Tournament ${suffix}`,
    drawProfiles: [{ drawSize: 4 }],
  });
  listedRecord.parentOrganisation = { organisationId: governingProviderId };
  await save(request, token, listedRecord);

  return {
    governingProviderId,
    governingAbbr,
    listedTournamentId: listedRecord.tournamentId,
    programmeA,
    programmeB,
    emptyProgramme,
    tournamentId: tournamentRecord.tournamentId,
    tournamentName,
    startDate: FIXTURE_DATE,
  };
}

async function save(request: APIRequestContext, token: string, tournamentRecord: any): Promise<void> {
  const saved = await request.post(`${SERVER}/factory/save`, {
    headers: authHeaders(token),
    data: { tournamentRecord },
  });
  const savedBody = await saved.json().catch(() => ({}));
  if (!savedBody?.success) {
    throw new Error(`seedParticipationFixture save ${tournamentRecord?.tournamentId}: ${JSON.stringify(savedBody)}`);
  }
}

/**
 * Remove the seeded fixture. `/factory/remove` drops the participation rows with the record, so a
 * run does not leave a growing season behind on a shared dev server.
 */
export async function cleanupParticipationFixture(
  request: APIRequestContext,
  token: string,
  fixture: ParticipationFixture,
): Promise<void> {
  for (const tournamentId of [fixture.tournamentId, fixture.listedTournamentId]) {
    await request.post(`${SERVER}/factory/remove`, {
      headers: authHeaders(token),
      data: { providerId: fixture.governingProviderId, tournamentId },
    });
  }
}
